"""Page rendering for the CFTK model-power calculator."""

from __future__ import annotations

import json
import traceback
import sys

import matplotlib.pyplot as plt
import pandas as pd
import streamlit as st

from apps.model_power_app_helpers import (
    EFFECT_DIRECTION_LABELS,
    PRECISION_MODES,
    SD_STAT_LABELS,
    AppValidationError,
    case_control_ratio,
    parse_sample_size_range,
    parse_sample_size_text,
    precision_settings,
    result_metadata,
    top_k_choices,
    top_k_training_warning,
    validate_analysis_inputs,
    validate_biomarker_inputs,
    validate_class_counts,
    validate_depth_selection,
    workload_warning,
)
from apps.model_power_app_runtime import (
    BLOCK_SIZE,
    DETECTION_ALPHA,
    GRID_SEED,
    N_BOOTSTRAP,
    NULL_SIMULATIONS_BY_PRECISION,
    REFERENCE_DIR,
    TEMPLATE_SEED,
    calculate_power_grid,
    load_available_depths,
)
from visualization.plot_model_power import plot_power_by_sample_size

POWER_METRICS = {
    "Probability of success (conservative)": {
        "column": "probability_of_success",
        "ylabel": "Probability of success",
        "description": (
            "Probability that a simulated study both rejects the full-pipeline "
            "no-signal null at alpha=0.05 and reaches the target CV AUC."
        ),
    },
    "Target-attainment probability": {
        "column": "target_attainment_probability",
        "ylabel": "Target-attainment probability",
        "description": (
            "Probability that the out-of-fold CV AUC reaches or exceeds the "
            "selected target AUC, regardless of statistical detection."
        ),
    },
    "Detection power": {
        "column": "detection_power",
        "ylabel": "Detection power",
        "description": (
            "Probability that the observed CV AUC is significant against a "
            "template-matched full-pipeline no-signal distribution."
        ),
    },
}

SUMMARY_COLUMNS = (
    "sample_size", "mean_depth", "detection_power",
    "target_attainment_probability", "probability_of_success",
    "detection_power_ci_low", "detection_power_ci_high",
    "target_attainment_probability_ci_low", "target_attainment_probability_ci_high",
    "probability_of_success_ci_low", "probability_of_success_ci_high",
    "mean_cv_auc", "mean_null_auc_threshold", "alpha", "target_auc",
    "mean_sensitivity_at_specificity", "mean_feature_recall",
    "mean_feature_precision", "mean_selection_jaccard", "n_templates",
    "simulations_per_template", "null_simulations_per_template",
    "total_simulations", "total_null_simulations",
)
PROBABILITY_COLUMNS = {
    column for column in SUMMARY_COLUMNS
    if any(token in column for token in ("power", "probability", "auc", "alpha", "sensitivity", "recall", "precision", "jaccard"))
}


def _format_summary_table(curve: pd.DataFrame, include_ci: bool) -> pd.DataFrame:
    columns = [
        c for c in SUMMARY_COLUMNS
        if c in curve.columns and (include_ci or not c.endswith(("_ci_low", "_ci_high")))
    ]
    table = curve.loc[:, columns].copy()
    for column in PROBABILITY_COLUMNS.intersection(table.columns):
        table[column] = table[column].map(lambda x: "" if pd.isna(x) else f"{float(x):.3f}")
    return table


def _parse_sample_sizes(mode: str, text: str, start: int, stop: int, step: int):
    parsed = parse_sample_size_text(text) if mode == "Comma-separated list" else parse_sample_size_range(start=start, stop=stop, step=step)
    return parsed.values, parsed.warnings


def _downloads(curve, signal, null, metadata):
    left, middle, right = st.columns(3)
    with left:
        st.download_button("Download power-curve CSV", curve.to_csv(index=False), "cftk_model_power_curve.csv", "text/csv")
    with middle:
        with st.expander("Replicate-level outputs"):
            st.download_button("Download signal-study CSV", signal.to_csv(index=False), "cftk_model_power_signal_replicates.csv", "text/csv")
            st.download_button("Download null-calibration CSV", null.to_csv(index=False), "cftk_model_power_null_replicates.csv", "text/csv")
    with right:
        st.download_button("Download settings JSON", json.dumps(metadata, indent=2, sort_keys=True) + "\n", "cftk_model_power_settings.json", "application/json")


def _metric_explanation():
    with st.expander("How the three power metrics differ", expanded=False):
        st.markdown(
            """
**Detection power**  
Probability that the study rejects the no-discrimination null at
$\\alpha=0.05$. The null AUC distribution is generated by rerunning the full
CV pipeline on matched no-signal cohorts.

**Target-attainment probability**  
Probability that the out-of-fold CV AUC reaches or exceeds the selected target
AUC, whether or not it is statistically significant against the null.

**Probability of success**  
Probability that both conditions are met: the model is statistically detected
and reaches the target AUC. This is the conservative default and is never
larger than either component probability.

Confidence intervals quantify Monte Carlo/template uncertainty around the
selected definition; they are not separate power definitions.
            """
        )


def main() -> None:
    st.set_page_config(page_title="CFTK Model-Development Power Calculator", layout="wide")
    st.markdown(
        """
        <style>.block-container {max-width: 1200px; padding-left: 2rem; padding-right: 2rem;}</style>
        """,
        unsafe_allow_html=True,
    )
    st.title("Model-Development Power Calculator")
    st.caption("Null-calibrated operating characteristics for an internal, cross-validated biomarker-discovery cohort.")
    _metric_explanation()

    try:
        available_depths = load_available_depths(str(REFERENCE_DIR))
    except Exception as exc:
        st.error(f"Could not read model-power depth manifest: {exc}")
        st.stop()

    with st.form("model_power_settings"):
        st.subheader("1. Study Design")
        left, right = st.columns(2)
        with left:
            sample_mode = st.radio("Total sample sizes", ["Comma-separated list", "Start / stop / step"], horizontal=True)
            sample_text = st.text_input("Sample-size list", "50, 100, 150, 200", disabled=sample_mode != "Comma-separated list")
            c1, c2, c3 = st.columns(3)
            sample_start = c1.number_input("Start", min_value=1, value=50, step=10, disabled=sample_mode != "Start / stop / step")
            sample_stop = c2.number_input("Stop", min_value=1, value=200, step=10, disabled=sample_mode != "Start / stop / step")
            sample_step = c3.number_input("Step", min_value=1, value=50, step=10, disabled=sample_mode != "Start / stop / step")
        with right:
            ratio_label = st.selectbox("Case-to-control ratio", ["1:3", "1:2", "1:1", "2:1", "3:1", "Custom"], index=2)
            custom_ratio = st.number_input("Custom n_cases / n_controls", min_value=0.01, value=1.0, step=0.05, format="%.2f", disabled=ratio_label != "Custom")
            defaults = tuple(d for d in (10, 30) if d in set(available_depths))
            selected_depths = st.multiselect("Mean sequencing depths", available_depths, default=defaults or available_depths[:1], format_func=lambda x: f"{x:g}x")
            target_auc = st.slider("Target cross-validated AUC", 0.60, 0.90, 0.75, 0.01)

        st.subheader("2. Biomarker Assumptions")
        left, right = st.columns(2)
        with left:
            n_features = st.selectbox("Number of candidate CpGs", [100, 250, 500, 1000, 2000], index=2)
            n_signal_cpgs = st.number_input("Number of true signal CpGs", min_value=1, max_value=int(n_features), value=min(20, int(n_features)), step=1)
            meth_diff = st.slider("Mean absolute methylation difference (absolute beta-value difference)", 0.01, 0.15, 0.05, 0.005, format="%.3f")
        with right:
            choices = top_k_choices(int(n_features))
            top_k = st.selectbox("Selected CpGs per training fold", choices, index=choices.index(10) if 10 in choices else 0)

        with st.expander("3. Advanced Settings", expanded=False):
            left, right = st.columns(2)
            with left:
                effect_sd = st.slider("Effect-size SD", 0.0, 0.05, 0.015, 0.005, format="%.3f")
                effect_label = st.selectbox("Effect direction", list(EFFECT_DIRECTION_LABELS), index=0)
                within_block_rho = st.slider("Within-block correlation", 0.0, 0.8, 0.20, 0.05)
                cv_folds = st.selectbox("Cross-validation folds", [3, 5, 10], index=1)
            with right:
                min_observed_fraction = st.slider("Minimum observed fraction", 0.30, 0.90, 0.50, 0.05)
                specificity_target = st.slider("Specificity operating point", 0.80, 0.99, 0.90, 0.01)
                sd_label = st.selectbox("SD uncertainty scenario", list(SD_STAT_LABELS), index=0, help="Lower SD is generally optimistic; upper SD is generally conservative.")

        st.subheader("4. Computation and Display Settings")
        c1, c2, c3 = st.columns(3)
        precision_mode = c1.selectbox("Precision mode", list(PRECISION_MODES), index=0)
        power_metric_label = c2.selectbox("Power definition", list(POWER_METRICS), index=0, help="Probability of success is the conservative joint criterion.")
        calculate_ci = c3.checkbox("Calculate confidence interval", value=False)
        st.caption(f"Detection significance is fixed at alpha={DETECTION_ALPHA:.2f}. Fast mode uses a coarse tail calibration; Standard mode is preferable for final reporting.")
        submitted = st.form_submit_button("Calculate", type="primary")

    if not submitted:
        return

    try:
        precision = precision_settings(precision_mode)
        null_n = NULL_SIMULATIONS_BY_PRECISION[precision_mode]
        sample_sizes, sample_warnings = _parse_sample_sizes(sample_mode, sample_text, int(sample_start), int(sample_stop), int(sample_step))
        ratio = case_control_ratio(ratio_label, custom_ratio=float(custom_ratio) if ratio_label == "Custom" else None)
        depths = validate_depth_selection(selected_depths)
        effect_direction = EFFECT_DIRECTION_LABELS[effect_label]
        sd_stat = SD_STAT_LABELS[sd_label]
        ci_method = "hierarchical_bootstrap" if calculate_ci else "none"
        n_bootstrap = N_BOOTSTRAP if calculate_ci else 0

        validate_class_counts(sample_sizes=sample_sizes, ratio=ratio, cv_folds=int(cv_folds))
        validate_biomarker_inputs(
            n_features=int(n_features), n_signal_cpgs=int(n_signal_cpgs), top_k=int(top_k),
            meth_diff=float(meth_diff), effect_sd=float(effect_sd), within_block_rho=float(within_block_rho),
            sd_stat=sd_stat, effect_direction=effect_direction,
        )
        validate_analysis_inputs(target_auc=float(target_auc), min_observed_fraction=float(min_observed_fraction), specificity_target=float(specificity_target), cv_folds=int(cv_folds))
        for message in sample_warnings:
            st.warning(message)
        warning = top_k_training_warning(top_k=int(top_k), sample_sizes=sample_sizes, ratio=ratio, cv_folds=int(cv_folds))
        if warning:
            st.warning(warning)
        warning = workload_warning(
            sample_sizes=sample_sizes, depths=depths, n_templates=precision["n_templates"],
            simulations_per_template=precision["simulations_per_template"] + null_n,
        )
        if warning:
            st.warning(warning)

        st.caption(
            f"Planned workload: {len(sample_sizes)} sample-size points × {precision['n_templates']} templates; "
            f"{precision['simulations_per_template']} signal + {null_n} null studies per template."
        )
        progress_bar = st.progress(0)
        progress_text = st.empty()

        def progress(completed, total, message):
            progress_bar.progress(0.0 if total <= 0 else min(max(completed / total, 0.0), 1.0))
            progress_text.caption(f"Step {min(completed, total)}/{total}: {message}")

        with st.spinner("Running signal studies and null calibration..."):
            result = calculate_power_grid(
                str(REFERENCE_DIR), tuple(depths), int(n_features), int(n_signal_cpgs), float(meth_diff),
                float(effect_sd), effect_direction, sd_stat, float(within_block_rho), BLOCK_SIZE,
                precision["n_templates"], TEMPLATE_SEED, tuple(sample_sizes), float(ratio), int(cv_folds),
                int(top_k), float(min_observed_fraction), float(target_auc), float(specificity_target),
                precision["simulations_per_template"], null_n, DETECTION_ALPHA, ci_method, n_bootstrap,
                GRID_SEED, _progress_callback=progress,
            )
        progress_bar.progress(1.0)
        progress_text.success("Calculation complete.")

        curve = result["power_curve"]
        metric_config = POWER_METRICS[power_metric_label]
        metric = metric_config["column"]
        plot_curve = curve.copy()
        if calculate_ci:
            plot_curve["power_ci_low"] = plot_curve[f"{metric}_ci_low"]
            plot_curve["power_ci_high"] = plot_curve[f"{metric}_ci_high"]

        st.subheader("Results")
        st.caption(metric_config["description"])
        fig, ax = plot_power_by_sample_size(
            plot_curve, power_metric=metric, show_ci=calculate_ci, target_power=0.80,
            title=f"{power_metric_label} by study size and sequencing depth",
        )
        ax.set_ylabel(metric_config["ylabel"])
        fig.tight_layout()
        st.pyplot(fig, use_container_width=True)
        plt.close(fig)
        st.dataframe(_format_summary_table(curve, calculate_ci), hide_index=True, use_container_width=True)

        st.info(
            f"Probability of success requires empirical null-calibrated p ≤ {DETECTION_ALPHA:.2f} "
            f"and CV AUC ≥ {target_auc:.2f}."
        )
        st.markdown(
            "- Null calibration reruns the complete CV pipeline with no case-control signal.\n"
            "- Feature recall and precision are simulation diagnostics because true signal CpGs are known.\n"
            "- Selection Jaccard summarizes fold-to-fold feature-set overlap.\n"
            "- These are internal model-development operating characteristics, not external-validation performance."
        )

        user_inputs = {
            "sample_sizes": list(sample_sizes), "case_to_control_ratio": ratio_label, "ratio": float(ratio),
            "depths": list(depths), "target_auc": float(target_auc), "detection_alpha": DETECTION_ALPHA,
            "power_definition": power_metric_label, "power_metric": metric, "n_features": int(n_features),
            "n_signal_cpgs": int(n_signal_cpgs), "meth_diff": float(meth_diff), "top_k": int(top_k),
            "effect_sd": float(effect_sd), "effect_direction": effect_direction,
            "within_block_rho": float(within_block_rho), "cv_folds": int(cv_folds),
            "min_observed_fraction": float(min_observed_fraction), "specificity_target": float(specificity_target),
            "sd_stat": sd_stat, "calculate_ci": bool(calculate_ci), "null_simulations_per_template": null_n,
        }
        metadata = result_metadata(
            user_inputs=user_inputs, precision_mode=precision_mode, template_seed=TEMPLATE_SEED,
            grid_seed=GRID_SEED, ci_method=ci_method, n_bootstrap=n_bootstrap,
        )
        metadata["run_metadata"] = result.get("run_metadata", {})
        metadata["reference"] = {"reference_dir": str(REFERENCE_DIR), "selected_depths": list(depths), "sd_stat": sd_stat}
        _downloads(curve, result["replicate_results"], result["null_replicate_results"], metadata)
    except AppValidationError as exc:
        st.error(str(exc))
    except Exception:
        st.error("The calculation could not be completed. Check the settings or reduce the workload.")
        print(traceback.format_exc(), file=sys.stderr)
